// frontend/src/config/INSTRUCTOR_FIELDS.js
// All 75 Instructor (Professor) Survey Fields
// type: "text" | "email" | "number" | "select" | "textarea" | "percentage"
// percentage = number input 0–100
// rating5    = number input 1–5
// rating10   = number input 1–10

export const INSTRUCTOR_FIELDS = [
  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 1 — Basic Information
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Basic Information",
    name: "q1_name",
    label: "Your Name",
    type: "text",
    required: true,
  },
  {
    section: "Basic Information",
    name: "q2_university",
    label: "Name of your University or Institution",
    type: "text",
    required: true,
  },
  {
    section: "Basic Information",
    name: "q108_email",
    label: "Academic Email ID",
    type: "email",
    required: true,
  },
  {
    section: "Basic Information",
    name: "q109_location",
    label: "City, State and Country where you teach",
    type: "text",
    required: true,
  },
  {
    section: "Basic Information",
    name: "q3_semester",
    label: "Semester for which you are filling this survey",
    type: "select",
    required: true,
    options: ["Fall", "Spring", "Summer", "Winter", "Other"],
  },
  {
    section: "Basic Information",
    name: "q3_4_text",
    label: "Semester — Other (please specify)",
    type: "text",
    required: false,
  },
  {
    section: "Basic Information",
    name: "year",
    label: "Academic Year",
    type: "text",
    required: true,
  },
  {
    section: "Basic Information",
    name: "q4_course",
    label: "Number and Full Title of the Course you are reviewing",
    type: "text",
    required: true,
  },
  {
    section: "Basic Information",
    name: "q111_degree_level",
    label: "Is this an Undergraduate (Bachelors) or Graduate (Masters) class?",
    type: "select",
    required: true,
    options: ["Undergraduate (Bachelors)", "Graduate (Masters)"],
  },
  {
    section: "Basic Information",
    name: "q104_student_count",
    label: "Approximately how many students are in this class?",
    type: "number",
    required: true,
    min: 1,
  },
  {
    section: "Basic Information",
    name: "q105_class_format",
    label: "Format of your class",
    type: "select",
    required: true,
    options: ["In-Person", "Hybrid", "Online", "Other"],
  },
  {
    section: "Basic Information",
    name: "q107_1_online_pct",
    label: "What percentage of your online class is synchronous (live)?",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Basic Information",
    name: "q6_role",
    label: "Your role in this class",
    type: "select",
    required: true,
    options: ["Professor", "Lecturer", "Teaching Assistant", "Other"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 2 — Overall Engagement
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Overall Engagement",
    name: "total_engage_score_p",
    label: "On a scale of 1 (Not Engaged) to 10 (Absolutely Engaged), to what extent do you think your pedagogy keeps students engaged?",
    type: "rating10",
    required: true,
    min: 1,
    max: 10,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 3 — Content Usage (frequency of use)
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Content Usage",
    name: "content_p_1",
    label: "Real world examples",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Content Usage",
    name: "content_p_2",
    label: "Personal experiences relevant to the topic",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Content Usage",
    name: "content_p_3",
    label: "Material that is directly applicable outside the class",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Content Usage",
    name: "content_p_4",
    label: "Current news or updated topics",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Content Usage",
    name: "content_p_5",
    label: "Real case studies",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Content Usage",
    name: "content_p_6",
    label: "Hypothetical case studies",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 4 — Relevance
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Relevance",
    name: "relevance_1p",
    label: "Allow students to share how they relate to the content you taught",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Relevance",
    name: "relevance_2p",
    label: "Persuade students to connect the material to their real life",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Relevance",
    name: "relevance_3p",
    label: "Keep the content entertaining",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Relevance",
    name: "relevance_4p",
    label: "Introduce a controversy through the content",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 5 — Discussion Methods
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Discussion Methods",
    name: "discuss_1p",
    label: "Use semi-structured discussion format to learn the materials",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Discussion Methods",
    name: "discuss_2p",
    label: "Encourage students to discuss / analyze / debate a given topic",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Discussion Methods",
    name: "discuss_3p",
    label: "Ask questions to students",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Discussion Methods",
    name: "discuss_4p",
    label: "Steer discussions so as to bring out innovative and progressive ideas",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Discussion Methods",
    name: "discuss_5p",
    label: "Design and structure the discussions in a way that forces analysis and conclusions rather than leaving it open",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Discussion Methods",
    name: "discuss_6p",
    label: "Design and structure the discussions in a way that ensures / requires participation from all students",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 6 — Active Participation
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Active Participation",
    name: "act_part_1p",
    label: "Create conditions that persuade every student to participate in activities other than class discussions",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_2p",
    label: "Require / mandate student participation in class activities",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_3p",
    label: "Administer group assignments to class",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_4p",
    label: "Involve students in hands-on activities",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_5p",
    label: "Use games, simulations etc. that provide opportunities for interaction with other classmates",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_6p",
    label: "Have students teach the class",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_7p",
    label: "Assign problem-solving activities to groups",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Active Participation",
    name: "act_part_8p",
    label: "Persuade students to be proactive in class",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 7 — Teaching Methods (as percentages, must sum to 100%)
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_1",
    label: "One-way lectures by professor",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_2",
    label: "Interactive lectures",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_3",
    label: "Powerpoint based one-way lectures",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_19",
    label: "Powerpoint based interactive lecture",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_5",
    label: "Individual pen-paper assignments",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_6",
    label: "Interactive / group pen-paper assignments",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_7",
    label: "Individual games",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_8",
    label: "Interactive games",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_9",
    label: "Individual online assignments",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_10",
    label: "Interactive / group online assignments",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_11",
    label: "Individual field assignments",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_12",
    label: "Group field assignments",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_13",
    label: "Fill in the blank notes",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_14",
    label: "Teaching props / teaching aids (replica skulls, real products, etc.)",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_15",
    label: "Articles or cases to read",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_16",
    label: "Any other method? (1)",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_17",
    label: "Any other method? (2)",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },
  {
    section: "Teaching Methods (% of time used)",
    name: "methods_p_18",
    label: "Any other method? (3)",
    type: "percentage",
    required: false,
    min: 0,
    max: 100,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 8 — Class Organization
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Class Organization",
    name: "cls_org_1p",
    label: "Your class materials are well organized",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Class Organization",
    name: "cls_org_2p",
    label: "Early on, you outline your expectations to students in clear terms",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Class Organization",
    name: "cls_org_3p",
    label: "You regularly clear up any confusion to avoid frustration from building up",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Class Organization",
    name: "cls_org_4p",
    label: "Your thoughts are well organized in each session",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Class Organization",
    name: "cls_org_5p",
    label: "Your notes and other materials are straight-forward, easy to follow",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 9 — Challenge Level
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Challenge Level",
    name: "challenge_level_1p",
    label: "You present unfamiliar material such that students can connect with it",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Challenge Level",
    name: "challenge_level_2p",
    label: "Students are frequently made to put their knowledge to test",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Challenge Level",
    name: "challenge_level_3p",
    label: "Students don't feel overwhelmed with homework and projects at any time of the semester",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Challenge Level",
    name: "challenge_level_4p",
    label: "Do your projects and assignments have just enough and optimal level of challenge to keep students motivated?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 10 — Connection with Students
  // ─────────────────────────────────────────────────────────────────────────
  {
    section: "Connection with Students",
    name: "cncts_1p",
    label: "How often do you know the students by name?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Connection with Students",
    name: "cncts_2p",
    label: "How often do you take time to know your students personally?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Connection with Students",
    name: "cncts_3p",
    label: "How often do you feel like you relate / connect with the students and their situations?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Connection with Students",
    name: "cncts_4p",
    label: "How often do you keep a friendly attitude towards your students?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Connection with Students",
    name: "cncts_5p",
    label: "How often do you engage students outside the classroom?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section: "Connection with Students",
    name: "cncts_6p",
    label: "How interested are you in the opinions and feedback of your students?",
    type: "select",
    required: false,
    options: ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
];

// ── Helper: get unique sections in order ──────────────────────────────────────
export const INSTRUCTOR_SECTIONS = [...new Set(INSTRUCTOR_FIELDS.map(f => f.section))];
