// frontend/src/config/STUDENT_FIELDS.js
// All 84 Student Survey Fields
// type: "text" | "email" | "number" | "select" | "textarea" | "percentage" | "rating10" | "rating13" | "rating5"

export const STUDENT_FIELDS = [
  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 2 — Overall Engagement
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Overall Engagement",
    name:      "total_engage_score_s",
    label:     "On a scale of 1 (Not Engaged) to 10 (Absolutely Engaged), to what extent do you think this class keeps students engaged?",
    type:      "rating10",
    required:  true,
    min:       1,
    max:       10,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 3 — Content (frequency of professor's usage)
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Content",
    name:      "content_s_1",
    label:     "Indicate how often your professor uses — Real world examples",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Content",
    name:      "content_s_2",
    label:     "Indicate how often your professor uses — Personal experiences relevant to the topic",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Content",
    name:      "content_s_3",
    label:     "Indicate how often your professor uses — Material that is directly applicable outside the class",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Content",
    name:      "content_s_4",
    label:     "Indicate how often your professor uses — Current news or updated topics",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Content",
    name:      "content_s_5",
    label:     "Indicate how often your professor uses — Real case studies",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Content",
    name:      "content_s_6",
    label:     "Indicate how often your professor uses — Hypothetical case studies",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 4 — Relevance
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Relevance",
    name:      "relevance_1s",
    label:     "Your professor allows the students to share how they relate to the content being taught",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Relevance",
    name:      "relevance_2s",
    label:     "Professor persuades students to connect the material to their real life",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Relevance",
    name:      "relevance_3s",
    label:     "Professor keeps the content entertaining",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Relevance",
    name:      "relevance_4s",
    label:     "Professor introduces a controversy through the content",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 5 — Discussion Methods
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Discussion Methods",
    name:      "discuss_1s",
    label:     "Your professor uses semi-structured discussion format to teach the materials",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Discussion Methods",
    name:      "discuss_2s",
    label:     "Professor encourages students to discuss / analyze / debate a given topic",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Discussion Methods",
    name:      "discuss_3s",
    label:     "Professor asks questions to students",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Discussion Methods",
    name:      "discuss_4s",
    label:     "Professor steers discussions so as to bring out innovative and progressive ideas",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Discussion Methods",
    name:      "discuss_5s",
    label:     "Professor designs and structures the discussions in a way that forces analysis and conclusions rather than leaving the topic open-ended",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Discussion Methods",
    name:      "discuss_6s",
    label:     "Professor structures the discussions in ways that ensure / require participation from all students",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 6 — Active Participation
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Active Participation",
    name:      "act_part_1s",
    label:     "Creates conditions that push every student to participate in all activities, besides class discussions",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_2s",
    label:     "Requires / mandates student participation in class activities",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_3s",
    label:     "Administers group assignments to class",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_4s",
    label:     "Involves students in hands-on activities",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_5s",
    label:     "Uses games, simulations etc. that provide opportunities for interaction with other classmates",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_6s",
    label:     "Has students teach the class",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_7s",
    label:     "Assigns problem-solving activities to groups",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Active Participation",
    name:      "act_part_8s",
    label:     "Persuades students to be proactive in class",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 7 — Teaching Methods (as percentages)
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_1",
    label:     "One-way lectures",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_2",
    label:     "Interactive lectures",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_3",
    label:     "Powerpoint based one-way lectures",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_5",
    label:     "Individual pen-paper assignments",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_6",
    label:     "Interactive / group pen-paper assignments",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_7",
    label:     "Individual / solo games",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_8",
    label:     "Interactive / group games",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_9",
    label:     "Individual / solo online assignments",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_10",
    label:     "Interactive / group online assignments",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_11",
    label:     "Individual field assignments",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_12",
    label:     "Group field assignments",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_13",
    label:     "Fill in the blank notes",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_14",
    label:     "Teaching props / teaching aids (replica skulls, real products, etc.)",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_15",
    label:     "Articles or cases to read",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_16",
    label:     "Any other method? (1)",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_16_text",
    label:     "Any other method? (1) — Please describe",
    type:      "text",
    required:  false,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_17",
    label:     "Any other method? (2)",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_17_text",
    label:     "Any other method? (2) — Please describe",
    type:      "text",
    required:  false,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_18",
    label:     "Any other method? (3)",
    type:      "percentage",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Teaching Methods (% of time used by professor)",
    name:      "methods_s_18_text",
    label:     "Any other method? (3) — Please describe",
    type:      "text",
    required:  false,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 8 — Class Organization
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Class Organization",
    name:      "cls_org_1s",
    label:     "Class materials provided by the professor are well organized",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Class Organization",
    name:      "cls_org_2s",
    label:     "Your professor outlines his/her expectations clearly to the students early on",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Class Organization",
    name:      "cls_org_3s",
    label:     "Your professor regularly clears up any confusion to avoid frustration from building up",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Class Organization",
    name:      "cls_org_4s",
    label:     "Your professor's thoughts are well organized in each session",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Class Organization",
    name:      "cls_org_5s",
    label:     "Notes and other materials provided by the professor are straight-forward, easy to follow",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 9 — Challenge Level
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Challenge Level",
    name:      "challenge_level_1s",
    label:     "Your professor presents unfamiliar material such that students can connect with it",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Challenge Level",
    name:      "challenge_level_2s",
    label:     "Students are frequently made to put their knowledge to test",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Challenge Level",
    name:      "challenge_level_3s",
    label:     "Students don't feel overwhelmed with homework and projects at any time of the semester",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Challenge Level",
    name:      "challenge_level_4s",
    label:     "Do the projects and assignments in this class have just enough and optimal level of challenge to keep you motivated?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 10 — Connection with Students
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Connection with Professor",
    name:      "cncts_1s",
    label:     "How often does your professor know the students by name?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Connection with Professor",
    name:      "cncts_2s",
    label:     "How often does your professor take time to know the students personally?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Connection with Professor",
    name:      "cncts_3s",
    label:     "How often does your professor seem to relate / connect with the students and their situation?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Connection with Professor",
    name:      "cncts_4s",
    label:     "How often does your professor keep a friendly attitude towards the students?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Connection with Professor",
    name:      "cncts_5s",
    label:     "How often does your professor engage students outside the classroom?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
  {
    section:   "Connection with Professor",
    name:      "cncts_6s",
    label:     "To what extent is your professor interested in the opinions and feedback of the students?",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SECTION 11 — Professor Attributes (sliders / scales)
  // ─────────────────────────────────────────────────────────────────────────
  {
    section:   "Professor Attributes",
    name:      "p_attrib_1",
    label:     "Slide the bar to indicate your teacher's excitement / energy for the class (0–100)",
    type:      "number",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_2",
    label:     "Slide the bar to indicate how laid back / relaxed your teacher's attitude towards the class is (0–100)",
    type:      "number",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_3",
    label:     "Slide the bar to indicate how much your teacher cares about the student's learning (0–100)",
    type:      "number",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_4",
    label:     "Slide the bar to indicate how much your teacher cares about the subject being taught (0–100)",
    type:      "number",
    required:  false,
    min:       0,
    max:       100,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_5",
    label:     "How knowledgeable do you think your professor is? (Scale 1–13)",
    type:      "number",
    required:  false,
    min:       1,
    max:       13,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_6",
    label:     "On a scale of 10, how easy is it to approach your professor if you need? (1–10)",
    type:      "rating10",
    required:  false,
    min:       1,
    max:       10,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_7",
    label:     "To what extent does your professor let their personality reflect in the interactions? (1–10)",
    type:      "rating10",
    required:  false,
    min:       1,
    max:       10,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_8",
    label:     "How high is your teacher's sense of humor? (1–10)",
    type:      "rating10",
    required:  false,
    min:       1,
    max:       10,
  },
  {
    section:   "Professor Attributes",
    name:      "p_attrib_9",
    label:     "How often does your teacher use humor, make fun of, or laugh at oneself? (1–5)",
    type:      "select",
    required:  false,
    options:   ["Never", "Rarely", "Sometimes", "Usually", "Always"],
  },
];

// ── Helper: get unique sections in order ──────────────────────────────────────
export const STUDENT_SECTIONS = [...new Set(STUDENT_FIELDS.map(f => f.section))];
